import argparse
import numpy as np
import onnxruntime as ort
from PIL import Image
from pathlib import Path

class AmigaONNXEnhancer:
    """
    Inference class for the optimized ONNX model.
    Expects a model generated by torch2onnx.py which includes 
    internal sRGB/Linear gamma and RGBA chunky preprocessing.
    """
    def __init__(self, model_path, use_gpu=True):
        # Select providers based on hardware and request
        providers = ['CPUExecutionProvider']
        if use_gpu:
            if 'CUDAExecutionProvider' in ort.get_available_providers():
                providers.insert(0, 'CUDAExecutionProvider')
            if 'MIGraphXExecutionProvider' in ort.get_available_providers():
                providers.insert(0, 'MIGraphXExecutionProvider')
        print(providers)

        print(f"Loading ONNX session with providers: {providers}")
        self.session = ort.InferenceSession(model_path, providers=providers)

        # Metadata from the model
        self.input_name = self.session.get_inputs()[0].name
        self.input_shape = self.session.get_inputs()[0].shape  # [1, 576, 752, 4]
        self.output_name = self.session.get_outputs()[0].name

    def process(self, input_path, output_path):
        """
        Loads an image, converts to RGBA UINT8, and runs inference.
        """
        # 1. Load and Prepare Image
        # The ONNX graph expects exactly 752x576. 
        # If the input differs, we resize it to match the framebuffer spec.
        with Image.open(input_path).convert("RGBA") as img:
            if img.size != (752, 576):
                img = img.resize((752, 576), Image.NEAREST)
            img_np = np.array(img).astype(np.uint8)

        # 2. Add Batch Dimension [H, W, C] -> [1, H, W, C]
        # Type must be UINT8 as defined in your ONNX conversion (Step 3a.1)
        input_tensor = np.expand_dims(img_np, axis=0)

        # 3. Inference
        # Note: Preprocessing (gamma, normalization, cropping) is inside the graph.
        outputs = self.session.run([self.output_name], {self.input_name: input_tensor})
        output_data = outputs[0]

        # 4. Post-processing
        # Remove batch dim and save. Output is already UINT8 RGBA.
        output_img_np = np.squeeze(output_data, axis=0)

        Image.fromarray(output_img_np, "RGBA").save(output_path)
        print(f"ONNX Processed: {input_path.name} -> {output_path}")

def main():
    parser = argparse.ArgumentParser(description='Amiga ONNX Enhancer Inference')
    parser.add_argument('--model', type=str, required=True, help='Path to .onnx model')
    parser.add_argument('--input', type=str, required=True, help='Input image path')
    parser.add_argument('--output', type=str, required=True, help='Output image path')
    parser.add_argument('--gpu', action='store_true', help='Use GPU execution')
    args = parser.parse_args()

    # Resolve paths
    in_path = Path(args.input)
    if not in_path.exists():
        # Check samples directory as fallback similar to infer.py
        base_dir = Path(__file__).parent
        in_path = base_dir / "samples" / in_path.name

    if not Path(args.model).exists():
        print(f"Error: ONNX model not found at {args.model}")
        return

    enhancer = AmigaONNXEnhancer(args.model, use_gpu=args.gpu)
    enhancer.process(in_path, Path(args.output))

if __name__ == "__main__":
    main()
