import os
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision.transforms import ToTensor, Compose, ToPILImage, RandomHorizontalFlip, RandomVerticalFlip
import torchvision.transforms.functional as F
from torchvision.utils import save_image
from torch.utils.tensorboard import SummaryWriter
from PIL import Image
from torchsummary import summary
import torchprofile
# from torchviz import make_dot # make_dot is often not needed for standard training
import argparse
import csv
import time
import sys
import glob
import random
from torch.amp import autocast, GradScaler
import shutil
import warnings
from collections import defaultdict
import re # Import regex module

# ----------------------------
# Helper function to parse filenames generated by generator.py
# This is the version that successfully parsed your filenames based on your debug output.
# ----------------------------
def parse_generated_filename(filename: str, verbose: int = 1) -> dict | None:
    """
    Parses a generated filename to extract its components based on the
    actual filename format found in your directory listing:
    Styled: <resolution>_<crop_x>_<crop_y>_s<scale>_r<rot>_<style_name_params>.png
    Target: target_<crop_x>_<crop_y>_s<scale>_r<rot>.png

    It does NOT include the original filename part from the directory name.
    """
    name, ext = os.path.splitext(filename)
    if ext.lower() != '.png':
        if verbose >= 3: print(f"DEBUG PARSE: Skipping file {filename} - not a PNG.")
        return None # Only process PNGs

    if verbose >= 3: print(f"DEBUG PARSE: Attempting to parse filename: {filename}")

    # Attempt to parse as a Target file first
    # Pattern: target_<crop_x>_<crop_y>_s<scale>_r<rot>
    target_match = re.match(r'^target_(?P<crop_x>-?\d+)_(?P<crop_y>-?\d+)_s(?P<scale_perc>\d+)_r(?P<rot_deg>-?\d+)$', name) # Added -? to rot_deg for safety
    # Added debug print to show if the target regex matched
    if verbose >= 3: print(f"DEBUG PARSE: Target regex match for '{name}': {target_match}")
    if target_match:
        try:
            parts = target_match.groupdict()
            crop_x = int(parts['crop_x'])
            crop_y = int(parts['crop_y'])
            scale_perc = int(parts['scale_perc'])
            rot_deg = int(parts['rot_deg'])

            # Return dictionary with parsed target components
            if verbose >= 3: print(f"DEBUG PARSE: Successfully parsed target: {filename}")
            return {
                'type': 'target',
                'crop_x': crop_x,
                'crop_y': crop_y,
                'scale_perc': scale_perc,
                'rot_deg': rot_deg,
                'style_name': None, # No style name for targets
                # Style parameters are None for target files
                'resolution': None, 'rgb': None, 'pal': None, 'dither': None,
                'filename': filename, # Store original filename
                # Include components needed for location key construction later (in gather function)
                'scale_part': f's{scale_perc}',
                'rot_part': f'r{rot_deg}',
            }
        except ValueError:
             if verbose >= 2: warnings.warn(f"ValueError during parsing target filename: {filename}. Skipping.")
             return None
        except Exception as e:
             if verbose >= 2: warnings.warn(f"Unexpected error parsing target filename {filename}: {e}. Skipping.")
             return None


    # Attempt to parse as a Styled file
    # Pattern: <resolution>_<crop_x>_<crop_y>_s<scale>_r<rot>_<style_name_params>
    # Style_name_params: rgb<rgb>_p<pal>_d<dither>
    # Captures the initial word as resolution, then coordinates, scale/rot, and the rest as style_name
    style_match = re.match(r'^(?P<resolution>\w+?)_(?P<crop_x>-?\d+)_(?P<crop_y>-?\d+)_s(?P<scale_perc>\d+)_r(?P<rot_deg>-?\d+)_(?P<style_name>.+)$', name) # Added ? to resolution, captured rest as style_name
    # Added debug print to show if the main styled regex matched
    if verbose >= 3: print(f"DEBUG PARSE: Styled regex match 1 for '{name}': {style_match}")

    if style_match:
        try:
            parts = style_match.groupdict()
            resolution = parts['resolution']
            crop_x = int(parts['crop_x'])
            crop_y = int(parts['crop_y'])
            scale_perc = int(parts['scale_perc'])
            rot_deg = int(parts['rot_deg'])
            style_name = parts['style_name'] # This is the part after r<rot>_ e.g., 'rgb666_p128_datkinson'

            if verbose >= 3: print(f"DEBUG PARSE: Extracted style_name: '{style_name}' from {filename}")

            # Attempt to parse the style name parameters from the style_name string
            # Expected format: rgb<rgb>_p<pal>_d<dither>
            style_params_match = re.match(r'^rgb(?P<rgb_val>\d+)_p(?P<pal_str>\w+)_d(?P<dither_name>[\w-]+)$', style_name)
            # Added debug print to show if the style parameter regex matched
            if verbose >= 3: print(f"DEBUG PARSE: Styled regex match 2 for '{style_name}': {style_params_match}")


            if not style_params_match:
                 # If the style_name part doesn't match the expected style parameter format
                 if verbose >= 2: warnings.warn(f"Styled filename part did not match expected style parameter format: {style_name} in file {filename}. Skipping.")
                 return None # Does not match expected styled parameter format

            try:
                style_params = style_params_match.groupdict()
                rgb_val_str = style_params['rgb_val'] # Keep as string initially
                pal_str = style_params['pal_str']
                dither_name = style_params['dither_name']

                # Convert rgb_val_str to integer
                rgb_val = int(rgb_val_str)

                # Convert palette string 'None' to actual None object
                pal = int(pal_str) if pal_str.lower() != 'none' else None

                # Dither method name (lowercase for consistency)
                dither_method_lower = dither_name.lower()

                # Return a dictionary representing the parsed styled file parameters
                if verbose >= 3: print(f"DEBUG PARSE: Successfully parsed styled: {filename}")
                return {
                    'type': 'style',
                    'crop_x': crop_x,
                    'crop_y': crop_y,
                    'scale_perc': scale_perc,
                    'rot_deg': rot_deg,
                    'resolution': resolution,
                    'style_name': style_name, # Store the full style name part e.g. 'lores_rgb888_pNone_dNone'
                    # Extract specific style parameters for easier access
                    'rgb': f"RGB{rgb_val}", # Store as 'RGBxxx' string
                    'pal': pal,             # Palette size (int or None)
                    'dither': dither_method_lower,  # Dither method name (lowercase string)
                    'filename': filename, # Store original filename
                    # Include components needed for location key construction later (in gather function)
                    'scale_part': f's{scale_perc}',
                    'rot_part': f'r{rot_deg}',
                }

            except ValueError:
                 # Handle errors during integer conversion for rgb_val or pal_str
                 if verbose >= 2: warnings.warn(f"ValueError during parsing styled filename parameters: {style_name} in file {filename}. Skipping.")
                 return None
            except Exception as e:
                 # Catch any other unexpected errors during parsing style parameters
                 if verbose >= 2: warnings.warn(f"Unexpected error parsing styled filename parameters {style_name} in file {filename}: {e}. Skipping.")
                 return None

        except ValueError:
             # Handle errors during integer conversion for crop_x, crop_y, scale_perc, rot_deg from the main match
             if verbose >= 2: warnings.warn(f"ValueError during initial parsing of filename {filename}. Skipping.")
             return None
        except Exception as e:
             if verbose >= 2: warnings.warn(f"Unexpected error during initial parsing of filename {filename}: {e}. Skipping.")
             return None

    # If the filename didn't match either expected target or styled format
    if verbose >= 2: warnings.warn(f"Filename '{filename}' did not match expected format after all attempts. Skipping.")
    return None


# ----------------------------
# Helper function to gather all samples from a directory
# This function constructs the crop_location_key using directory name and parsed components.
# ----------------------------
def gather_all_samples_from_directory(directory_path: str, expected_crop_size: tuple[int, int], styles_to_include: set | None = None, verbose: int = 1):
    """
    Walks a directory, identifies target and styled crop files using the
    filename format, and gathers all available (styled_path, target_path)
    pairs grouped by unique crop location (directory name + parsed components).

    Args:
        directory_path: The root directory to walk (e.g., the generator's train output dir).
        expected_crop_size: The expected (width, height) for validation of the loaded images.
                               This should be the size of the crops produced by generator.py.
        styles_to_include: A set of specific style name strings to include. If None, all available styles are included.
        verbose (int): Verbosity level for warnings/messages.

    Returns:
        A list of (styled_img_path, target_img_path) tuples representing available pairs.
    """
    if not os.path.isdir(directory_path):
        raise FileNotFoundError(f"Data directory not found: {directory_path}")

    # Dictionary to group parsed file information by their unique crop location key.
    # Key: (original_directory_name, crop_x, crop_y, scale_part, rot_part)
    # Value: List of parsed file dictionaries found for this unique crop instance
    grouped_files_by_location = defaultdict(list)

    if verbose >= 1: print(f"Scanning directory {directory_path} for sample files...")
    # os.walk traverses the directory tree. Root will be like .../generator_output/train/image123_without_ext
    for root, dirs, files in os.walk(directory_path):
        # We expect subdirectories within the main directory_path
        # The name of the subdirectory is typically the original filename part that generator used
        original_directory_name = os.path.basename(root)

        # Only process files directly within subdirectories of directory_path, not in directory_path itself
        # This check assumes your generator output has subdirectories like test2/train/5128/
        if os.path.abspath(root) == os.path.abspath(directory_path):
             if verbose >= 3: print(f"DEBUG GATHER: Skipping root directory: {root}")
             continue # Skip the root directory itself


        for filename in files:
            # Use the standalone parser to get structured info from the filename itself
            # Pass verbose level to the parser
            parsed_info = parse_generated_filename(filename, verbose=verbose)

            # Add a debug print to show the parsed info and its keys
            if verbose >= 3 and isinstance(parsed_info, dict):
                 print(f"DEBUG GATHER: Parsed info for {filename}: {parsed_info}")
                 print(f"DEBUG GATHER: Keys in parsed_info for {filename}: {list(parsed_info.keys())}")


            # If parsing was successful and contains necessary components for the key
            if isinstance(parsed_info, dict) and all(key in parsed_info for key in ['crop_x', 'crop_y', 'scale_part', 'rot_part']):
                 full_file_path = os.path.join(root, filename)
                 parsed_info['full_path'] = full_file_path

                 # Construct the unique location key using directory name and parsed components
                 crop_location_key = (
                     original_directory_name,
                     parsed_info['crop_x'],
                     parsed_info['crop_y'],
                     parsed_info['scale_part'],
                     parsed_info['rot_part']
                 )
                 # We don't need to add the key to parsed_info anymore if not used downstream,
                 # but it can be helpful for debugging.

                 # Group files by this constructed location key
                 grouped_files_by_location[crop_location_key].append(parsed_info)
                 if verbose >= 3: print(f"DEBUG GATHER: Grouping file {filename} under key {crop_location_key}")
            elif parsed_info is not None:
                 # This case happens if parse_generated_filename returned a dict but is missing key components
                 if verbose >= 2: warnings.warn(f"Parsed info for {filename} is missing key components for location key. Skipping.")
            # else: parse_generated_filename returned None and already warned if verbose >= 2 or on errors


    if verbose >= 1: print(f"Finished scanning. Found files in {len(grouped_files_by_location)} unique crop locations.")
    if verbose >= 2: print(f"Debug Gather: Grouped files by location count: {len(grouped_files_by_location)}")
    if verbose >= 2 and styles_to_include is not None: print(f"Debug Gather: Styles to include filter: {styles_to_include}")


    # List to hold all available (styled_input_path, target_path) pairs across all locations
    available_samples_pool: list[tuple[str, str]] = []

    # Iterate through the grouped files to create the list of available samples
    if verbose >= 2: print("Debug Gather: Pairing styled files with target files...")
    # Add a print statement before this loop to see if there are any keys to iterate over
    if verbose >= 3: print(f"DEBUG GATHER: Keys in grouped_files_by_location: {list(grouped_files_by_location.keys())}")

    for crop_location_key, files_info_list in grouped_files_by_location.items():
        if verbose >= 3: print(f"\nDEBUG GATHER: Processing location key {crop_location_key}")
        target_file_info = None
        styled_files_info: list[dict] = []

        # Separate target from styled files within the group and apply style filtering
        for file_info in files_info_list:
            if file_info['type'] == 'target':
                target_file_info = file_info
                if verbose >= 3: print(f"DEBUG GATHER: Found target file info for {crop_location_key}: {file_info['filename']}")
            elif file_info['type'] == 'style':
                # Apply the styles_to_include filter here
                # The style_name is extracted from the filename by the parser
                if styles_to_include is None or (file_info.get('style_name') is not None and file_info['style_name'] in styles_to_include):
                     styled_files_info.append(file_info)
                     if verbose >= 3: print(f"DEBUG GATHER: Included styled file {file_info['filename']} for {crop_location_key}")
                elif verbose >= 3 and file_info.get('style_name') is not None:
                     print(f"DEBUG GATHER: Skipping styled file {file_info['full_path']} with style '{file_info['style_name']}' due to style filter.")
                elif verbose >= 3: # Handle cases where style_name might be missing
                     print(f"DEBUG GATHER: Skipping styled file {file_info.get('full_path', 'unknown')} due to missing style name or style filter.")


        # If a target file was found AND there are included styled files at this location, create pairs
        if target_file_info and styled_files_info:
            target_path = target_file_info['full_path']

            # Optional: Validate target image size
            # Assuming style image sizes match targets at generation, validating target is sufficient.
            try:
                 # Check size validation only once per crop location key
                 with Image.open(target_path) as img:
                      if img.size != expected_crop_size:
                           warnings.warn(f"Target image {target_path} has unexpected dimensions: {img.size}. Expected: {expected_crop_size}. Skipping all samples for this crop location.")
                           continue # Skip all samples for this crop location if target size is wrong
                 if verbose >= 3: print(f"DEBUG GATHER: Target size for {target_path} matched expected {expected_crop_size}.")

            except FileNotFoundError: # Handle case where target file path is parsed but file is missing
                 warnings.warn(f"Target image file not found: {target_path}. Skipping all samples for this crop location.")
                 continue
            except Exception as e: # Catch other potential errors during image open/size check
                 warnings.warn(f"Could not read target image {target_path} for size validation: {e}. Skipping all samples for this crop location.")
                 continue


            for styled_file_info in styled_files_info:
                styled_path = styled_file_info['full_path']
                # Add the (styled_input_path, target_path) pair to the pool of available samples
                available_samples_pool.append((styled_path, target_path))
                if verbose >= 3:
                     print(f"DEBUG GATHER: Added pair: ({os.path.basename(styled_path)}, {os.path.basename(target_path)})")


    if verbose >= 1: print(f"Sample gathering complete. Found {len(available_samples_pool)} total sample pairs matching criteria.")

    return available_samples_pool


# ----------------------------
# Dataset for Super-Resolution
# Adapted for random sub-cropping from generator's output crops.
# ----------------------------
class SRDataset(Dataset):
    """
    Dataset for loading styled input crops and corresponding target crops
    from a pre-defined list of (styled_path, target_path) pairs (generator output).
    Performs random sub-cropping and synchronized flips on these loaded crops.
    """
    # Keep __init__ signature similar to the version that worked, but add train_crop_size
    def __init__(self, sample_pairs_list: list[tuple[str, str]], generator_output_crop_size: tuple[int, int], train_crop_size: tuple[int, int], num_samples: int):
        """
        Args:
            sample_pairs_list: A list of (styled_img_path, target_img_path) tuples (generator output).
            generator_output_crop_size: The expected (width, height) of the images loaded from disk.
                                        This is the size of the crops generated by generator.py.
                                        Used for validation and sub-cropping calculations.
            train_crop_size: The desired (width, height) of the random sub-crops for training.
                                 This is the size the model expects.
            num_samples: The declared length of the dataset for one epoch.
                         __len__ will return this value. Samples are drawn randomly
                         from the available pool (sample_pairs_list).
        """
        self.available_samples_pool: list[tuple[str, str]] = sample_pairs_list # Directly assign the list
        self.generator_output_w, self.generator_output_h = generator_output_crop_size
        self.train_crop_w, self.train_crop_h = train_crop_size
        self.num_samples = num_samples # The declared length of the dataset for an epoch

        # Validation: Ensure train_crop_size is not larger than generator_output_crop_size
        if self.train_crop_w > self.generator_output_w or self.train_crop_h > self.generator_output_h:
             # This is a configuration error. The training crop cannot be larger than the source crop.
             raise ValueError(f"Train crop size ({self.train_crop_w}x{self.train_crop_h}) is larger than generator output crop size ({self.generator_output_w}x{self.generator_output_h}). Ensure --crop_size is <= the size of crops produced by generator.py.")


        # Check if the pool of available samples is empty
        if not self.available_samples_pool:
            warnings.warn(f"SRDataset initialized with an empty sample pool.")


        self.to_tensor = ToTensor()
        # to_pil is not needed

    # __len__ method remains the same
    def __len__(self):
        """
        Returns the declared length of the dataset, determined by num_samples.
        """
        return self.num_samples

    # __getitem__ method adapted for random sub-cropping
    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Loads a randomly selected sample pair (generator output crops),
        performs a random sub-crop, and applies synchronized flips.

        Ignores the input index `idx`.
        """
        # Ensure there are samples available to draw from
        if not self.available_samples_pool:
            raise IndexError("SRDataset pool is empty. Cannot draw samples.")

        # Implement a simple retry mechanism for image loading errors
        max_retries = 5
        for attempt in range(max_retries):
            try:
                # Randomly select an index from the list of available generator output sample pairs
                pool_size = len(self.available_samples_pool)
                if pool_size == 0:
                     raise IndexError("SRDataset pool is empty. Cannot draw samples.")
                random_idx = random.randint(0, pool_size - 1)

                # Get the file paths for the styled input and the target image using the random index
                styled_img_path, target_img_path = self.available_samples_pool[random_idx]

                # Load the images using Pillow. Convert to RGB.
                styled_img_pil = Image.open(styled_img_path).convert('RGB')
                target_img_pil = Image.open(target_img_path).convert('RGB')

                # Optional: Validate loaded image dimensions (should match generator_output_crop_size)
                # This check is now a warning as the primary validation is in __init__
                if styled_img_pil.size != (self.generator_output_w, self.generator_output_h):
                     warnings.warn(f"Styled image {styled_img_path} has unexpected dimensions: {styled_img_pil.size}. Expected: {(self.generator_output_w, self.generator_output_h)}. Sub-cropping may behave unexpectedly.")
                if target_img_pil.size != (self.generator_output_w, self.generator_output_h):
                     warnings.warn(f"Target image {target_img_path} has unexpected dimensions: {target_img_pil.size}. Expected: {(self.generator_output_w, self.generator_output_h)}. Sub-cropping may behave unexpectedly.")


                break # Exit retry loop if loading is successful

            except FileNotFoundError:
                 # If the file is missing, it's a permanent error for this path
                 warnings.warn(f"Attempt {attempt+1}/{max_retries}: Generator output file not found: {styled_img_path} or {target_img_path}. Skipping and retrying with another sample pair.")
                 if attempt == max_retries - 1:
                      raise FileNotFoundError(f"Failed to load generator output files after {max_retries} attempts for pair ({styled_img_path}, {target_img_path})")
                 # Retry with another random sample immediately
                 continue
            except Exception as e:
                 # For other errors (like 'cannot identify'), retry
                 warnings.warn(f"Attempt {attempt+1}/{max_retries}: Error loading generator output images for sample ({styled_img_path}, {target_img_path}): {e}. Retrying.")
                 if attempt == max_retries - 1:
                      raise RuntimeError(f"Failed to load generator output images after {max_retries} attempts for pair ({styled_img_path}, {target_img_path})")
                 time.sleep(0.1) # Wait a bit before retrying


        # --- Perform Random Sub-Cropping ---
        img_width, img_height = styled_img_pil.size # Should ideally be generator_output_crop_size


        # Calculate maximum possible top-left coordinates for the training crop
        # Ensure crop does not go out of bounds within the loaded generator output crop
        max_crop_x = img_width - self.train_crop_w
        max_crop_y = img_height - self.train_crop_h

        # Check if loaded image is large enough for the desired training crop
        if max_crop_x < 0 or max_crop_y < 0:
             # This should ideally be caught by the generator_output_crop_size validation in __init__
             # but handle defensively in case image sizes vary.
             warnings.warn(f"Generator output crop ({img_width}x{img_height}) is smaller than training crop size ({self.train_crop_w}x{self.train_crop_h}) for sample ({styled_img_path}, {target_img_path}). Skipping and retrying.")
             return self.__getitem__(idx) # Retry with another random sample


        # Randomly select top-left crop coordinates for the sub-crop, ensuring they are divisible by 2
        # Use random.randrange(start, stop, step)
        # Stop is exclusive, so max_crop_x + 1 is needed to include max_crop_x if it's even
        # Ensure start is not negative
        crop_x = random.randrange(0, max_crop_x + 1, 2) if max_crop_x >= 0 else 0
        crop_y = random.randrange(0, max_crop_y + 1, 2) if max_crop_y >= 0 else 0


        # Extract the smaller training crops (LR and HR)
        lr_crop_pil = styled_img_pil.crop((crop_x, crop_y, crop_x + self.train_crop_w, crop_y + self.train_crop_h))
        hr_crop_pil = target_img_pil.crop((crop_x, crop_y, crop_x + self.train_crop_w, crop_y + self.train_crop_h))


        # Convert Pillow images to PyTorch tensors (scales to [0, 1])
        # Ensure images are in RGB format before converting to tensor
        lr_t = self.to_tensor(lr_crop_pil.convert("RGB"))
        hr_t = self.to_tensor(hr_crop_pil.convert("RGB"))


        # Apply synchronized random horizontal flip to the SMALLER crops
        if random.random() < 0.5:
            lr_t = F.hflip(lr_t)
            hr_t = F.hflip(hr_t)

        # Apply synchronized random vertical flip to the SMALLER crops
        if random.random() < 0.5:
            lr_t = F.vflip(lr_t)
            hr_t = F.vflip(hr_t)

        # Return the LR input and HR target tensors (from the sub-crops)
        return lr_t, hr_t

# inference_on_directory, save_training_stats, load_last_epoch and train_model functions remain.
# Need to ensure train_model is compatible with standard DataLoader output (LR, HR tensors).

# TensorBoard writer - Keep outside functions that might be pickled by dataloaders
writer = SummaryWriter(log_dir='runs/transformer_experiment')
average_inference_time = 0.0

# Helper function for batch size argument (assuming needed based on original code comment)
def add_size_argument(parser, name, default, help):
    """Adds a size argument (e.g., --batch_size) that can be an integer or a tuple."""
    class SizeAction(argparse.Action):
        def __call__(self, parser, namespace, values, option_string=None):
            if isinstance(values, str):
                try:
                    # Attempt to parse as an integer
                    setattr(namespace, self.dest, int(values))
                except ValueError:
                    # Attempt to parse as a tuple of integers (e.g., '32 16')
                    try:
                        parts = list(map(int, values.split()))
                        if len(parts) == 1:
                             setattr(namespace, self.dest, parts[0]) # Still allow single int
                        else:
                             setattr(namespace, self.dest, tuple(parts)) # Store as tuple
                    except ValueError:
                        raise argparse.ArgumentError(self, f"invalid size value: {values} (expected integer or space-separated integers)")
            else: # Should already be an integer or tuple if not from command line string
                 setattr(namespace, self.dest, values)

    parser.add_argument(name, default=default, type=str, action=SizeAction, help=help)